package constants

import (
	"os"
	"syscall"
)

const (
	META_COMMAND_SUCCESS              = "META_COMMAND_SUCCESS"
	META_COMMAND_FAIL                 = "META_COMMAND_FAIL"
	META_COMMAND_UNRECOGNIZED_COMMAND = "META_COMMAND_UNRECOGNIZED_COMMAND"
	META_COMMAND_EXIT                 = "META_COMMAND_EXIT"

	PREPARE_SUCCESS                = "PREPARE_SUCCESS"
	PREPARE_UNRECOGNIZED_STATEMENT = "PREPARE_UNRECOGNIZED_STATEMENT"
	PREPARE_SYNTAX_ERROR           = "PREPARE_SYNTAX_ERROR"
	// PREPARE_NEGATIVE_ID            = "PREPARE_NEGATIVE_ID" // NOTE: Not needed since Regex will not match negative numbers
	PREPARE_STRING_TOO_LONG = "PREPARE_STRING_TOO_LONG"
	PREPARE_NON_POSITIVE_ID = "PREPARE_NON_POSITIVE_ID"

	STATEMENT_INSERT = "STATEMENT_INSERT"
	STATEMENT_SELECT = "STATEMENT_SELECT"
)

const (
	EXECUTE_SUCCESS        = "EXECUTE_SUCCESS"
	EXECUTE_TABLE_FULL     = "EXECUTE_TABLE_FULL"
	EXECUTE_STATEMENT_FAIL = "EXECUTE_STATEMENT_FAIL"
)

const (
	COLUMN_USERNAME_SIZE = 32
	COLUMN_EMAIL_SIZE    = 255
)

const (
	ID_SIZE       = 4
	USERNAME_SIZE = 32
	EMAIL_SIZE    = 255

	ID_OFFSET       = 0
	USERNAME_OFFSET = ID_OFFSET + ID_SIZE
	EMAIL_OFFSET    = USERNAME_OFFSET + USERNAME_SIZE
	ROW_SIZE        = ID_SIZE + USERNAME_SIZE + EMAIL_SIZE

	PAGE_SIZE       = 4096
	TABLE_MAX_PAGES = 100
	ROWS_PER_PAGE   = PAGE_SIZE / ROW_SIZE
	TABLE_MAX_ROWS  = ROWS_PER_PAGE * TABLE_MAX_PAGES
)

const (
	DEFAULT_FILE_MODE = os.FileMode(0644)
)

const (
	O_RDWR  = syscall.O_RDWR
	O_CREAT = syscall.O_CREAT
	S_IWUSR = syscall.S_IWUSR
	S_IRUSR = syscall.S_IRUSR
)
